name: Build (CMake + Ninja)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      CC: gcc
      CXX: g++

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Clone dependency
        run: |
          git init ./Nova-Engine
          cd ./Nova-Engine
          git remote add origin https://github.com/Steak-Fish/Nova-Engine.git
          git fetch --depth 1 origin 0c13d23b2454a32647507470907d8995a4d5014f
          git checkout FETCH_HEAD

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            pkg-config \
            libglfw3-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            librtaudio-dev \
            librtmidi-dev

      - name: Configure CMake
        run: |
          cmake \
            -S app \
            -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: build-bin
          path: bin/
          if-no-files-found: error
