name: Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        build_type: [Debug, Release]

    env:
      CC: gcc
      CXX: g++

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            pkg-config \
            libglfw3-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            librtaudio-dev \
            librtmidi-dev \
            libglm-dev

      - name: Configure CMake (${{ matrix.build_type }})
        run: |
          cmake \
            -S app \
            -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build (${{ matrix.build_type }})
        run: |
          cmake --build build

      - name: Upload binaries (${{ matrix.build_type }})
        uses: actions/upload-artifact@v4
        with:
          name: build-bin-${{ matrix.build_type }}
          path: bin/
          if-no-files-found: error